name = "americafirst-co-nz"
main = "src/worker.js"
compatibility_date = "2026-09-19"

routes = [
  { pattern = "americafirst.co.nz/*", zone_name = "americafirst.co.nz" },
  { pattern = "www.americafirst.co.nz/*", zone_name = "americafirst.co.nz" }
]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
